### ISSUE TITLE
Add `AddColoredNoise`

### ISSUE THREAD

**Issue by mmxgn** [iver56/audiomentations#263]
This is already available in `torch-audiomentations`.

**Comment by atamazian** [comment]
Can you assign this issue to me?

**Comment by iver56** [comment]
@atamazian It's ~90% done already, I would say. There's a PR for it, but the work on completing it it has had a hiatus for some time. There's a TODO list for the completion here:
https://github.com/iver56/audiomentations/pull/277#issuecomment-1709763475

@mmxgn Do you have time to do the `f decay in dB per octave instead of dB (best to do it before merge, or else there will be a breaking API change later)` item? I would be happy to do the rest

**Comment by atamazian** [comment]
@iver56 I haven't noticed that there's a PR for it. In that case, I think it would be better for me to work on some other issue.

**Comment by mmxgn** [comment]
@iver56 Yep, had forgotten about it. Will get to it soon.

**Comment by iver56** [comment]
Thanks 🙏

**Comment by mmxgn** [comment]
Closing as completed by https://github.com/iver56/audiomentations/pull/277

**Comment by mmxgn** [comment]
Closing as completed by https://github.com/iver56/audiomentations/pull/277
