### ISSUE TITLE
WrongMultichannelAudioShape assumptions

### ISSUE THREAD

**Issue by timlod** [iver56/audiomentations#289]
Hi,

I'm having an issue with the how the wrong audio shape is determined:
`    if samples.shape[0] > samples.shape[1]:` - but perhaps my case could be deemed to contrived:
I work with really short snippets of audio (say 256 samples), of which I'll have thousands.
What I want to do is efficiently augment all of them, batch-wise. 
So what I'd like to do is just treat each example as a channel, and process them all at once. This will lead to situations where I'd call an augmentation on a shape of (1000, 256), which will fail due to the check that shape[0] should be <= shape[1].

I'm assuming that the processing doesn't actually rely on multiple channels and is essentially a vectorized operation (which may be wrong), and I also assume that the set of augmentations I'm using doesn't require a runup of samples (as my examples are so short, temporal effects may not work).

Is there a way for me to do this correctly, or will I have to call them one by one?

**Comment by timlod** [comment]
It's realtime audio onset classification. Given an audio onset, you wait the shortest possible time and use the few samples since onset to classify the sound source. Sample rate would be 44.1kHz+ - I'm not sure yet whether higher sample rates (and perhaps a bit of ultrasound that might capture, depending on the microphone) are useful. But in general there would usually be at most 5ms of audio available, regardless of sample rate.

**Comment by iver56** [comment]
Interesting use case :) An assumption audiomentations does is that all the channels in a multichannel audio snippet "belong together". So if I for example apply SevenBandParametricEQ to a multichannel audio snippet, all the channels will have the same EQ curve applied. In your case it sounds like you want to treat the channels independently, because they are different sounds, and you would want to augment each sound independently instead of with the same parameters. Am I right?

Btw, when I changed WrongMultichannelAudioShape from a warning to an error I remember having in mind that some users might actually have a use case for extreme shapes (although I could not think of a use case back then), and I also thought that users with unusual use cases can also fork the library and adapt it to their needs, like removing the line of code that throws the error.

**Comment by iver56** [comment]
One project that does indeed support batched processing of many examples (with unique/independent augmentations parameters for each example) is https://github.com/asteroid-team/torch-audiomentations. It's not as mature and well maintained as audiomentations, but it could fit your use case of doing batched processing on thousands of audio snippets

**Comment by timlod** [comment]
Thanks for the insight!

I think applying the same effect for each example is fine - as the examples themselves are already different, and I call each augmentation several times, leading to ultimately many different effects being applied. 
So that's actually what I expected it would do. Nothing wrong with applying different transforms on each example of course - but in that case the function can't be vectorized in any case, and the performance/efficiency viewpoint is moot, I think. That is unless we can trade off time vs space here and pre-compute some effecting vectors which can then be applied in a vectorized way - I guess whether that can be done efficiently depends on the effect applied, I haven't looked deeply into it.

I've changed to just looping for now and applying augmentations to examples individually. If I find this gets too slow, I might look into the alternatives or patch audiomentations, thanks for pointing it out!

**Comment by iver56** [comment]
Some transforms, like SevenBandParametricEQ and AirAbsorption do indeed just use a loop internally instead of a vectorized/batched approach for the different channels. Other transforms, like AddGaussianNoise and TanhDistortion have code that deal with all channels in one go, without an inefficient loop.

**Comment by iver56** [comment]
I hope this helps: https://github.com/iver56/audiomentations/pull/291

**Comment by timlod** [comment]
Thanks! For now it's fine, but I imagine there'll be cases where also this limit is easily exceeded.
Perhaps there'd be a chance to set a flag to turn the check off altogether?
