### ISSUE TITLE
Can't open .wav file correctly

### ISSUE THREAD

**Issue by xwJohn** [iver56/audiomentations#41]
After run:  
python -m demo.demo  

There will be generate some wav files in output folder, but I can't open it with an error message:
Windows Media Player encountered a problem while playing the file.

**Comment by iver56** [comment]
Right. I guess that's because Windows Media Player doesn't support wav files with float32 data type.

Here are your options:

1. Get a better media player, such as VLC. Audacity can also open float32 files.
2. Modify the demo script, so it writes the output files in int16 format instead. This format is more widely supported. Pull requests are welcome! :)

**Comment by iver56** [comment]
Here's a function that can convert float32 audio to int16:
```

def convert_float_samples_to_int16(y, clamp_values=True):
    """
    Convert floating-point numpy array of audio samples to int16.
    :param y:
    :param clamp_values: Clip extreme values to the range [-1.0, 1.0]. This can be done to avoid
        integer overflow or underflow, which results in wrap distortion, which sounds worse than
        clipping distortion.
    :return:
    """
    if not issubclass(y.dtype.type, np.floating):
        raise ValueError("input samples not floating-point")

    if clamp_values:
        y = clip_extreme_values(y)

    return (y * np.iinfo(np.int16).max).astype(np.int16)
```

**Comment by xwJohn** [comment]
Hi Iver,

Thanks for your reply.

Actually it's because the sound_np.dtype == np.float64, Windows Media Player can't open this format.

It can opened after I changed the sound_np.dtype to np.float32 by:

sound_np = sound_np.astype(np.float32)
