### ISSUE TITLE
Spectral version of transforms

### ISSUE THREAD

**Issue by LordOfLuck** [iver56/audiomentations#59]
Hi, is it possible to apply the transforms on spectral audio representations? Say I have mel spectrograms stored on disc and want to run on the fly augmentations. Augmentations directly in spectral domain would be useful since I could store the features instead of the audios and save disc space. Many of the augmentations probably require spectral domain internally anyway. Are there any plans to support this scenario?

**Comment by iver56** [comment]
Yes, definitely! That issue (feature request) is actually already discussed here: https://github.com/iver56/audiomentations/issues/43

If you would like to contribute, that would be awesome

If you need something _right now_, you could check out alternatives at https://github.com/iver56/audiomentations#alternatives

Closing this issue since it duplicates #43

**Comment by LordOfLuck** [comment]
Hey, thanks for swift response and sorry for duplicate. Will check the provided links.

**Comment by iver56** [comment]
Some spectrogram transforms are now available in master. See https://github.com/iver56/audiomentations/pull/60

Thoughts?

**Comment by LordOfLuck** [comment]
@iver56 Thanks for the update. The APIs look pretty good :) Are there plans to support impulse response for spectograms too?

**Comment by iver56** [comment]
Thanks! Maybe
