### ISSUE TITLE
Waveform to Spectrogram function

### ISSUE THREAD

**Issue by omerferhatt** [iver56/audiomentations#81]
Adding convert function (like ToSpec(..) )will be useful when using one augmentation pipeline. 

Waveform -> Augmentation -> Convert to Spectrogram -> Augmentation -> Augmented Spectrogram

**Comment by iver56** [comment]
I'm afraid this might be out of scope for audiomentations, since there are so many possible ways to convert audio to spectrogram. Here are some notes that outline the complexity involved in adding this feature:

Some STFT implementations:

* librosa (numpy/scipy)
* kapre (tensorflow/keras)
* torch-stft (pytorch)
* asteroid-filterbanks (pytorch)
* julius (pytorch)

STFT has a lot of parameters, like window size, hop length (AKA stride), power, window function

Then there is optionally a conversion to mel spectrogram. And maybe conversion from magnitude to decibel. Perhaps also a standardization step.

Some people might want to use a trainable waveform to spectrogram transform.

Some people rather want to use wavelet transform.

Some people want to keep the phase instead of discarding it.

---

Maybe it's within reach to add a user-implementable abstract base class? Along with a librosa-based reference implementation?

**Comment by atamazian** [comment]
I'm not sure if audiomentations needs to have such functionality; there're plenty of packages which can do it (like mentioned in the post above).

**Comment by iver56** [comment]
Yep, let's close this one
